customhost = "employee.c1aathpyjru1.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "limweisiang-employee"
customregion = "us-east-1"
